### ISSUE TITLE
не работает

### ISSUE THREAD

**Issue by hghuoiuopuut** [Amir585/Select-Menu-Role#2]

**Comment by Amir585** [comment]
Напиш в дс Amir#9349
 
 
--

Amir Zaremuk

**Comment by hghuoiuopuut** [comment]
> Напиш в дс Amir#9349     -- Amir Zaremuk    
> Понедельник, 8 августа 2022, 0:00 +03:00 от getar ***@***.***>:     еще раз не работает. — Reply to this email directly, view it on GitHub , or unsubscribe . You are receiving this because you are subscribed to this thread. Message ID: <Amir585/Select-Menu-Role/issues/2 @ github . com>

я тебя добавил в друзья в дискорде прим
и

**Comment by hghuoiuopuut** [comment]
> Напиш в дс Amir#9349     -- Amir Zaremuk    
> Понедельник, 8 августа 2022, 0:00 +03:00 от getar ***@***.***>:     еще раз не работает. — Reply to this email directly, view it on GitHub , or unsubscribe . You are receiving this because you are subscribed to this thread. Message ID: <Amir585/Select-Menu-Role/issues/2 @ github . com>

Прими

**Comment by Amir585** [comment]
Извини, отправь ещё раз, ты потерялся
 
 
--

Amir Zaremuk
 
  
>Понедельник, 15 августа 2022, 0:40 +03:00 от getar ***@***.***>:
> 
> 
>Напиш в дс Amir#9349     -- Amir Zaremuk    
>Понедельник, 8 августа 2022, 0:00 +03:00 от getar  @ .***>:     еще раз не работает. — Reply to this email directly, view it on GitHub , or unsubscribe . You are receiving this because you are subscribed to this thread. Message ID: < /issues/2 @ github . com>
Прими

**Comment by hghuoiuopuut** [comment]
> Извини, отправь ещё раз, ты потерялся     -- Amir Zaremuk    
> Понедельник, 15 августа 2022, 0:40 +03:00 от getar ***@***.***>:     Напиш в дс Amir#9349     -- Amir Zaremuk     Понедельник, 8 августа 2022, 0:00 +03:00 от getar @ .***>:     еще раз не работает. — Reply to this email directly, view it on GitHub , or unsubscribe . You are receiving this because you are subscribed to this thread. Message ID: < /issues/2 @ github . com>
> Прими — Reply to this email directly, view it on GitHub , or unsubscribe . You are receiving this because you commented. Message ID: <Amir585/Select-Menu-Role/issues/2/1214454007 @ github . com>

ник fanged

**Comment by hghuoiuopuut** [comment]
> _No description provided._



> _No description provided._
